Repository matteobruni/object-gui, pull requests merged in 2020-10, with the labels that each got.

#38 Added Purple theme
  src/scss/themes/_purple.scss
  src/ts/Editor.ts
Labels: size/S

#40 Hebrew Translation of README.md
  README-IL.md
  README.md
Labels: size/M

#41 Added 3 new themes
  src/scss/themes/_moonlight.scss
  src/scss/themes/_orange.scss
  src/scss/themes/_sunlight.scss
  src/ts/Editor.ts
Labels: size/M

#42 Added gold theme
  src/scss/editor.scss
  src/scss/themes/_gold.scss
  src/ts/Editor.ts
Labels: size/S

#43 added brown theme
  src/scss/editor.scss
  src/scss/themes/_brown.scss
  src/ts/Editor.ts
Labels: size/S

#44 Add grey theme
  src/scss/editor.scss
  src/scss/themes/_grey.scss
  src/ts/Editor.ts
Labels: size/S

#46 add neu-moon theme: a neumorphic version of the moonlight theme
  src/scss/editor.scss
  src/scss/themes/_neumoon.scss
  src/ts/Editor.ts
Labels: size/S

#51 Pink theme added
  src/scss/editor.scss
  src/scss/themes/_pink.scss
  src/ts/Editor.ts
Labels: size/S

#52 Add Nautilus theme
  src/scss/editor.scss
  src/scss/themes/_nautilus.scss
  src/ts/Editor.ts
Labels: size/S

#54 added cyan theme
  src/scss/editor.scss
  src/scss/themes/_cyan.scss
  src/ts/Editor.ts
Labels: size/S

#57 Added yellow theme
  src/scss/editor.scss
  src/scss/themes/_yellow.scss
  src/ts/Editor.ts
Labels: size/S

#59 added neu-pink
  src/scss/editor.scss
  src/scss/themes/_neupink.scss
  src/ts/Editor.ts
Labels: size/S

#68 Add Night Sky theme; related to #36
  src/scss/editor.scss
  src/scss/themes/_night-sky.scss
  src/ts/Editor.ts
Labels: size/S

#76 Add one-dark theme
  src/scss/editor.scss
  src/scss/themes/_one-dark.scss
  src/ts/Editor.ts
Labels: size/S

#77 Added: Neu-GreySun
  src/scss/editor.scss
  src/scss/themes/_neugreysun.scss
  src/ts/Editor.ts
Labels: size/S

#78 Add gameboy theme
  src/scss/editor.scss
  src/scss/themes/_gameboy.scss
  src/ts/Editor.ts
Labels: size/S

#85 Added theme trafficlights.
  src/scss/editor.scss
  src/scss/themes/trafficlights.scss
  src/ts/Editor.ts
Labels: size/S

#87 Added three themes Ashgrey, Tuftsblue and GreyOrange
  src/scss/editor.scss
  src/scss/themes/_ashgrey.scss
  src/scss/themes/_greyorange.scss
  src/scss/themes/_tuftsblue.scss
  src/ts/Editor.ts
Labels: size/M

#90 Peach & Starbell themes added
  src/scss/editor.scss
  src/scss/themes/_peach.scss
  src/scss/themes/_starbell.scss
  src/ts/Editor.ts
Labels: size/M

#98 Added neu-gold, neu-silver, neu-ecofriendly and fedex themes
  src/scss/editor.scss
  src/scss/themes/_fedex.scss
  src/scss/themes/_neuecofriendly.scss
  src/scss/themes/_neugold.scss
  src/scss/themes/_neusilver.scss
  src/ts/Editor.ts
Labels: size/M

#104 Added neu-orange, neu-blue, neu-expedia, neu-caribbean themes
  src/scss/editor.scss
  src/scss/themes/_neublue.scss
  src/scss/themes/_neucaribbean.scss
  src/scss/themes/_neuexpedia.scss
  src/scss/themes/_neuorange.scss
  src/ts/Editor.ts
Labels: size/L
